version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: fidentra-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: fidentra
      POSTGRES_PASSWORD: fidentra123
      POSTGRES_DB: fidentra

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: